var searchData=
[
  ['part_0',['Part',['../md_source_2best-practices_2large-models.html#autotoc_md105',1,'3. 大 Mesh 使用 Part'],['../md_source_2user-guide_2mesh-display.html#autotoc_md316',1,'3. Mesh Part'],['../md_source_2user-guide_2visibility.html#autotoc_md393',1,'7. Object Display Part'],['../md_source_2api_2viewer-types.html#autotoc_md83',1,'Object Display Part']]],
  ['part_20增量更新_1',['5. Part 增量更新',['../md_source_2user-guide_2mesh-display.html#autotoc_md322',1,'']]],
  ['part_20更新_2',['3. Mesh Part 更新',['../md_source_2best-practices_2incremental-update.html#autotoc_md91',1,'']]],
  ['part_20id_3',['4. Mesh ID / Part ID',['../md_source_2best-practices_2topology-ids.html#autotoc_md114',1,'']]],
  ['part_20style_4',['11. Part Style',['../md_source_2user-guide_2mesh-display.html#autotoc_md328',1,'']]],
  ['pattern_5',['Line Pattern',['../md_source_2user-guide_2preview.html#autotoc_md342',1,'']]],
  ['pbr_20与工程材质_6',['PBR 与工程材质',['../index.html#autotoc_md242',1,'']]],
  ['pbr_20appearance_7',['4. PBR Appearance',['../md_source_2user-guide_2appearance-material.html#autotoc_md253',1,'']]],
  ['pen_8',['5. Pen',['../md_source_2user-guide_2input-events.html#autotoc_md308',1,'']]],
  ['pending_20frame_20work_9',['4. Pending Frame Work',['../md_source_2user-guide_2viewer-lifecycle.html#autotoc_md381',1,'']]],
  ['persistent_20与_20interaction_20style_10',['8. Persistent 与 Interaction Style',['../md_source_2user-guide_2appearance-material.html#autotoc_md258',1,'']]],
  ['pick_11',['Pick',['../md_source_2user-guide_2selection-picking.html#autotoc_md352',1,'2. Query Pick'],['../md_source_2api_2hts-viewer-sdk.html#autotoc_md33',1,'7. Selection &amp;amp; Pick'],['../md_source_2concepts_2selection-target.html#autotoc_md164',1,'Query Pick']]],
  ['pick_20与_20selection_12',['5. 查询式 Pick 与 Selection',['../md_source_2concepts_2selection-target.html#autotoc_md163',1,'']]],
  ['picking_13',['Picking',['../md_source_2user-guide_2selection-picking.html',1,'Selection &amp; Picking'],['../index.html#autotoc_md241',1,'Selection &amp;amp; Picking']]],
  ['plane_20color_14',['5. Grid Plane Color',['../md_source_2user-guide_2coordinate-grid-hud.html#autotoc_md277',1,'']]],
  ['plane_20wave_15',['Plane Wave',['../md_source_2api_2display-data.html#autotoc_md12',1,'']]],
  ['plane_20wave_20主要参数_16',['6. Plane Wave 主要参数',['../md_source_2user-guide_2overlay.html#autotoc_md336',1,'']]],
  ['plane_20wave_20glyph_17',['5. Plane Wave Glyph',['../md_source_2user-guide_2overlay.html#autotoc_md335',1,'']]],
  ['point_18',['Point',['../md_source_2user-guide_2selection-picking.html#autotoc_md362',1,'12. Feature Point'],['../md_source_2api_2viewer-types.html#autotoc_md80',1,'Feature Point']]],
  ['preset_19',['5. Material Preset',['../md_source_2user-guide_2appearance-material.html#autotoc_md255',1,'']]],
  ['preview_20',['Preview',['../md_source_2user-guide_2preview.html#autotoc_md339',1,'1. 基本 Preview'],['../md_source_2getting-started_2introduction.html#autotoc_md183',1,'3.5 Preview'],['../md_source_2concepts_2data-lifetime.html#autotoc_md133',1,'4. Preview'],['../md_source_2user-guide_2preview.html#autotoc_md345',1,'5. Has Preview'],['../md_source_2best-practices_2transparency.html#autotoc_md122',1,'5. Preview'],['../md_source_2api_2hts-viewer-sdk.html#autotoc_md31',1,'6. Preview'],['../md_source_2user-guide_2preview.html',1,'Preview'],['../md_source_2api_2viewer-types.html#autotoc_md86',1,'Preview'],['../md_source_2glossary.html#autotoc_md230',1,'Preview']]],
  ['preview_20与工程_20overlay_21',['Preview 与工程 Overlay',['../index.html#autotoc_md243',1,'']]],
  ['preview_20axis_22',['6. Preview Axis',['../md_source_2user-guide_2preview.html#autotoc_md346',1,'']]],
  ['preview_20marker_23',['7. Preview Marker',['../md_source_2user-guide_2preview.html#autotoc_md347',1,'']]],
  ['preview_20style_24',['2. Preview Style',['../md_source_2user-guide_2preview.html#autotoc_md340',1,'']]],
  ['preview_20transform_25',['Preview Transform',['../md_source_2user-guide_2preview.html#autotoc_md343',1,'3. Preview Transform'],['../md_source_2best-practices_2incremental-update.html#autotoc_md93',1,'5. Preview Transform']]],
  ['programmatic_20selection_26',['7. Programmatic Selection',['../md_source_2user-guide_2selection-picking.html#autotoc_md357',1,'']]]
];
