var searchData=
[
  ['h_0',['h',['../md_source_2api_2overview.html#autotoc_md67',1,'HtsDisplayData.h'],['../md_source_2api_2overview.html#autotoc_md68',1,'HtsMeshData.h'],['../md_source_2api_2overview.html#autotoc_md70',1,'HtsViewerApi.h'],['../md_source_2api_2overview.html#autotoc_md65',1,'HtsViewerSdk.h'],['../md_source_2api_2overview.html#autotoc_md69',1,'HtsViewerSettings.h'],['../md_source_2api_2overview.html#autotoc_md66',1,'HtsViewerTypes.h']]],
  ['has_20preview_1',['5. Has Preview',['../md_source_2user-guide_2preview.html#autotoc_md345',1,'']]],
  ['haspendingframework_2',['&lt;span class=&quot;tt&quot;&gt;hasPendingFrameWork&lt;/span&gt;',['../md_source_2api_2hts-viewer-sdk.html#autotoc_md18',1,'']]],
  ['hover_3',['Hover',['../md_source_2user-guide_2selection-picking.html#autotoc_md361',1,'11. Hover'],['../md_source_2api_2hts-viewer-sdk.html#autotoc_md35',1,'8. Hover']]],
  ['hover_20summary_4',['4. Hover Summary',['../md_source_2user-guide_2diagnostics.html#autotoc_md285',1,'']]],
  ['hts_20viewer_20demo_5',['Hts Viewer Demo',['../md_source_2getting-started_2viewer-demo.html',1,'']]],
  ['hts_20viewer_20sdk_20是什么_6',['1. Hts Viewer SDK 是什么',['../md_source_2getting-started_2introduction.html#autotoc_md176',1,'']]],
  ['hts_20viewer_20sdk_202_200_7',['Hts Viewer SDK 2.0',['../index.html',1,'']]],
  ['htscolor4f_3a_3aa_8',['1. HtsColor4f::a',['../md_source_2best-practices_2transparency.html#autotoc_md118',1,'']]],
  ['htsdisplaybodydata_9',['HtsDisplayBodyData',['../md_source_2api_2display-data.html#autotoc_md7',1,'']]],
  ['htsdisplaybodykind_10',['HtsDisplayBodyKind',['../md_source_2api_2display-data.html#autotoc_md3',1,'']]],
  ['htsdisplaydata_20api_20reference_11',['HtsDisplayData API Reference',['../md_source_2api_2display-data.html',1,'']]],
  ['htsdisplaydata_20h_12',['HtsDisplayData.h',['../md_source_2api_2overview.html#autotoc_md67',1,'']]],
  ['htsdisplayedgedata_13',['HtsDisplayEdgeData',['../md_source_2api_2display-data.html#autotoc_md6',1,'']]],
  ['htsdisplayfacedata_14',['HtsDisplayFaceData',['../md_source_2api_2display-data.html#autotoc_md5',1,'']]],
  ['htsdisplaymeshdata_15',['HtsDisplayMeshData',['../md_source_2user-guide_2display-data.html#autotoc_md290',1,'2. HtsDisplayMeshData'],['../md_source_2api_2display-data.html#autotoc_md10',1,'HtsDisplayMeshData']]],
  ['htsdisplayobjectdata_16',['HtsDisplayObjectData',['../md_source_2user-guide_2display-data.html#autotoc_md294',1,'3. HtsDisplayObjectData'],['../md_source_2api_2display-data.html#autotoc_md9',1,'HtsDisplayObjectData']]],
  ['htsdisplayshapetype_17',['HtsDisplayShapeType',['../md_source_2api_2display-data.html#autotoc_md2',1,'']]],
  ['htsdisplayvertexdata_18',['HtsDisplayVertexData',['../md_source_2api_2display-data.html#autotoc_md8',1,'']]],
  ['htsfaceoverlaydata_19',['HtsFaceOverlayData',['../md_source_2api_2display-data.html#autotoc_md11',1,'']]],
  ['htsimportedmaterialdata_20',['HtsImportedMaterialData',['../md_source_2api_2display-data.html#autotoc_md4',1,'']]],
  ['htsmaterialappearance_21',['HtsMaterialAppearance',['../md_source_2api_2viewer-types.html#autotoc_md85',1,'']]],
  ['htsmaterialappearance_3a_3atransparency_22',['2. HtsMaterialAppearance::transparency',['../md_source_2best-practices_2transparency.html#autotoc_md119',1,'']]],
  ['htsmeshdata_20api_20reference_23',['HtsMeshData API Reference',['../md_source_2api_2mesh-data.html',1,'']]],
  ['htsmeshdata_20h_24',['HtsMeshData.h',['../md_source_2api_2overview.html#autotoc_md68',1,'']]],
  ['htsmeshdisplaydata_25',['HtsMeshDisplayData',['../md_source_2user-guide_2mesh-display.html#autotoc_md315',1,'2. HtsMeshDisplayData'],['../md_source_2api_2mesh-data.html#autotoc_md60',1,'HtsMeshDisplayData']]],
  ['htsmeshdisplaymode_26',['HtsMeshDisplayMode',['../md_source_2api_2mesh-data.html#autotoc_md52',1,'']]],
  ['htsmeshdisplayoptions_27',['HtsMeshDisplayOptions',['../md_source_2api_2mesh-data.html#autotoc_md53',1,'']]],
  ['htsmeshelementtype_28',['HtsMeshElementType',['../md_source_2api_2mesh-data.html#autotoc_md51',1,'']]],
  ['htsmeshpartdata_29',['HtsMeshPartData',['../md_source_2api_2mesh-data.html#autotoc_md54',1,'']]],
  ['htsmeshpartstyle_30',['HtsMeshPartStyle',['../md_source_2api_2mesh-data.html#autotoc_md61',1,'']]],
  ['htsmeshstatistics_31',['HtsMeshStatistics',['../md_source_2api_2mesh-data.html#autotoc_md62',1,'']]],
  ['htsrendermaterial_3a_3aopacity_32',['3. HtsRenderMaterial::opacity',['../md_source_2best-practices_2transparency.html#autotoc_md120',1,'']]],
  ['htsselectiontarget_33',['3. HtsSelectionTarget',['../md_source_2concepts_2object-topology-model.html#autotoc_md144',1,'']]],
  ['htsviewerapi_20h_34',['HtsViewerApi.h',['../md_source_2api_2overview.html#autotoc_md70',1,'']]],
  ['htsviewersdk_20api_20reference_35',['HtsViewerSdk API Reference',['../md_source_2api_2hts-viewer-sdk.html',1,'']]],
  ['htsviewersdk_20h_36',['HtsViewerSdk.h',['../md_source_2api_2overview.html#autotoc_md65',1,'']]],
  ['htsviewersettings_20api_20reference_37',['HtsViewerSettings API Reference',['../md_source_2api_2viewer-settings.html',1,'']]],
  ['htsviewersettings_20h_38',['HtsViewerSettings.h',['../md_source_2api_2overview.html#autotoc_md69',1,'']]],
  ['htsviewertypes_20api_20reference_39',['HtsViewerTypes API Reference',['../md_source_2api_2viewer-types.html',1,'']]],
  ['htsviewertypes_20h_40',['HtsViewerTypes.h',['../md_source_2api_2overview.html#autotoc_md66',1,'']]],
  ['hud_41',['Coordinate System, Grid &amp;amp; HUD',['../md_source_2user-guide_2coordinate-grid-hud.html',1,'']]],
  ['hud_20axis_42',['3. HUD Axis',['../md_source_2user-guide_2coordinate-grid-hud.html#autotoc_md275',1,'']]],
  ['hud_20grid_43',['12. Axis / HUD / Grid',['../md_source_2api_2hts-viewer-sdk.html#autotoc_md43',1,'']]]
];
