var searchData=
[
  ['sample_0',['Sample',['../md_source_2getting-started_2licensing.html#autotoc_md197',1,'4. Sample'],['../md_source_2glossary.html#autotoc_md236',1,'Sample']]],
  ['samples_20工程中的_20sdk_1',['1. Samples 工程中的 SDK',['../md_source_2getting-started_2installation.html#autotoc_md168',1,'']]],
  ['samples_20的区别_2',['1. Demo 与 Samples 的区别',['../md_source_2getting-started_2viewer-demo.html#autotoc_md219',1,'']]],
  ['scale_20bar_3',['2. Scale Bar',['../md_source_2user-guide_2coordinate-grid-hud.html#autotoc_md274',1,'']]],
  ['scenetype_4',['&lt;span class=&quot;tt&quot;&gt;sceneType&lt;/span&gt;',['../md_source_2user-guide_2display-data.html#autotoc_md291',1,'']]],
  ['screen_5',['Screen',['../md_source_2user-guide_2selection-picking.html#autotoc_md364',1,'14. World to Screen'],['../md_source_2concepts_2coordinate-and-screen.html#autotoc_md127',1,'2. World to Screen']]],
  ['screen_20ray_6',['13. Screen Ray',['../md_source_2user-guide_2selection-picking.html#autotoc_md363',1,'']]],
  ['screen_20to_20world_20ray_7',['1. Screen to World Ray',['../md_source_2concepts_2coordinate-and-screen.html#autotoc_md126',1,'']]],
  ['sdk_8',['1. Samples 工程中的 SDK',['../md_source_2getting-started_2installation.html#autotoc_md168',1,'']]],
  ['sdk_20依赖_9',['3. 不根据 Demo 推断 SDK 依赖',['../md_source_2best-practices_2integration-boundary.html#autotoc_md99',1,'']]],
  ['sdk_20公开边界_10',['SDK 公开边界',['../md_source_2concepts_2public-boundary.html',1,'']]],
  ['sdk_20安装与目录_11',['SDK 安装与目录',['../md_source_2getting-started_2installation.html',1,'']]],
  ['sdk_20授权_20api_12',['2. SDK 授权 API',['../md_source_2getting-started_2licensing.html#autotoc_md195',1,'']]],
  ['sdk_20是什么_13',['1. Hts Viewer SDK 是什么',['../md_source_2getting-started_2introduction.html#autotoc_md176',1,'']]],
  ['sdk_20的公开边界_14',['SDK 的公开边界',['../index.html#autotoc_md246',1,'']]],
  ['sdk_20集成边界_15',['商业 SDK 集成边界',['../md_source_2best-practices_2integration-boundary.html',1,'']]],
  ['sdk_202_200_16',['Hts Viewer SDK 2.0',['../index.html',1,'']]],
  ['select_17',['4. Box Select',['../md_source_2user-guide_2selection-picking.html#autotoc_md354',1,'']]],
  ['select_20all_18',['5. Select All',['../md_source_2user-guide_2selection-picking.html#autotoc_md355',1,'']]],
  ['select_20at_19',['3. Select At',['../md_source_2user-guide_2selection-picking.html#autotoc_md353',1,'']]],
  ['selection_20',['Selection',['../md_source_2user-guide_2mesh-display.html#autotoc_md327',1,'10. Selection'],['../md_source_2user-guide_2camera-view.html#autotoc_md266',1,'2. Fit Selection'],['../md_source_2getting-started_2introduction.html#autotoc_md181',1,'3.3 Semantic Selection'],['../md_source_2concepts_2selection-target.html#autotoc_md163',1,'5. 查询式 Pick 与 Selection'],['../md_source_2user-guide_2selection-picking.html#autotoc_md357',1,'7. Programmatic Selection'],['../md_source_2user-guide_2selection-picking.html#autotoc_md358',1,'8. Clear Selection'],['../md_source_2api_2viewer-types.html#autotoc_md79',1,'Selection'],['../md_source_2concepts_2selection-target.html#autotoc_md165',1,'Selection']]],
  ['selection_20回写_21',['6. Selection 回写',['../md_source_2best-practices_2topology-ids.html#autotoc_md116',1,'']]],
  ['selection_20appearance_22',['7. Selection Appearance',['../md_source_2user-guide_2appearance-material.html#autotoc_md257',1,'']]],
  ['selection_20center_23',['4. Selection Center',['../md_source_2user-guide_2camera-view.html#autotoc_md268',1,'']]],
  ['selection_20dimming_24',['10. Selection Dimming',['../md_source_2user-guide_2selection-picking.html#autotoc_md360',1,'']]],
  ['selection_20display_20state_25',['9. Selection Display State',['../md_source_2user-guide_2selection-picking.html#autotoc_md359',1,'']]],
  ['selection_20mode_26',['1. Selection Mode',['../md_source_2user-guide_2selection-picking.html#autotoc_md351',1,'']]],
  ['selection_20pick_27',['7. Selection &amp;amp; Pick',['../md_source_2api_2hts-viewer-sdk.html#autotoc_md33',1,'']]],
  ['selection_20picking_28',['Selection Picking',['../md_source_2user-guide_2selection-picking.html',1,'Selection &amp; Picking'],['../index.html#autotoc_md241',1,'Selection &amp;amp; Picking']]],
  ['selection_20query_29',['6. Selection Query',['../md_source_2user-guide_2selection-picking.html#autotoc_md356',1,'']]],
  ['selection_20set_30',['6. 完整 Selection Set',['../md_source_2concepts_2selection-target.html#autotoc_md166',1,'']]],
  ['selection_20summary_31',['3. Selection Summary',['../md_source_2user-guide_2diagnostics.html#autotoc_md284',1,'']]],
  ['selection_20target_32',['Selection Target',['../md_source_2concepts_2selection-target.html',1,'Selection Target'],['../md_source_2glossary.html#autotoc_md229',1,'Selection Target']]],
  ['selection_20visibility_33',['1. Selection Visibility',['../md_source_2user-guide_2visibility.html#autotoc_md387',1,'']]],
  ['semantic_20selection_34',['3.3 Semantic Selection',['../md_source_2getting-started_2introduction.html#autotoc_md181',1,'']]],
  ['set_35',['6. 完整 Selection Set',['../md_source_2concepts_2selection-target.html#autotoc_md166',1,'']]],
  ['settings_36',['Settings',['../md_source_2api_2hts-viewer-sdk.html#autotoc_md23',1,'2. Settings'],['../md_source_2api_2viewer-settings.html#autotoc_md72',1,'Color Settings'],['../md_source_2api_2viewer-settings.html#autotoc_md73',1,'Numeric Settings'],['../md_source_2user-guide_2settings.html',1,'Viewer Settings']]],
  ['shapeversion_37',['&lt;span class=&quot;tt&quot;&gt;shapeVersion&lt;/span&gt;',['../md_source_2user-guide_2display-data.html#autotoc_md292',1,'']]],
  ['shouldclose_38',['&lt;span class=&quot;tt&quot;&gt;shouldClose&lt;/span&gt;',['../md_source_2api_2hts-viewer-sdk.html#autotoc_md19',1,'']]],
  ['show_20all_39',['2. Show All',['../md_source_2user-guide_2visibility.html#autotoc_md388',1,'']]],
  ['stable_20ids_40',['Stable IDs',['../md_source_2user-guide_2mesh-display.html#autotoc_md318',1,'']]],
  ['staged_20mesh_20update_41',['Staged Mesh Update',['../md_source_2concepts_2data-lifetime.html#autotoc_md132',1,'3. Staged Mesh Update'],['../md_source_2user-guide_2mesh-display.html#autotoc_md323',1,'6. Staged Mesh Update'],['../md_source_2glossary.html#autotoc_md234',1,'Staged Mesh Update']]],
  ['standalone_42',['Standalone',['../md_source_2user-guide_2viewer-lifecycle.html#autotoc_md378',1,'']]],
  ['start_43',['Quick Start',['../md_source_2getting-started_2quick-start.html',1,'']]],
  ['state_44',['9. Selection Display State',['../md_source_2user-guide_2selection-picking.html#autotoc_md359',1,'']]],
  ['statistics_45',['12. Statistics',['../md_source_2user-guide_2mesh-display.html#autotoc_md329',1,'']]],
  ['stats_46',['2. Display Stats',['../md_source_2user-guide_2diagnostics.html#autotoc_md283',1,'']]],
  ['style_47',['Style',['../md_source_2user-guide_2appearance-material.html#autotoc_md250',1,'1. Viewer Display Style'],['../md_source_2user-guide_2mesh-display.html#autotoc_md328',1,'11. Part Style'],['../md_source_2user-guide_2preview.html#autotoc_md340',1,'2. Preview Style'],['../md_source_2best-practices_2incremental-update.html#autotoc_md94',1,'6. Visibility &amp;amp; Style'],['../md_source_2user-guide_2appearance-material.html#autotoc_md258',1,'8. Persistent 与 Interaction Style'],['../md_source_2api_2hts-viewer-sdk.html#autotoc_md37',1,'9. Display Style'],['../md_source_2api_2viewer-types.html#autotoc_md81',1,'Display Style'],['../md_source_2glossary.html#autotoc_md233',1,'Display Style']]],
  ['submitinput_48',['&lt;span class=&quot;tt&quot;&gt;submitInput&lt;/span&gt;',['../md_source_2api_2hts-viewer-sdk.html#autotoc_md21',1,'']]],
  ['summary_49',['Summary',['../md_source_2user-guide_2diagnostics.html#autotoc_md284',1,'3. Selection Summary'],['../md_source_2user-guide_2diagnostics.html#autotoc_md285',1,'4. Hover Summary']]],
  ['system_50',['6. Coordinate System',['../md_source_2user-guide_2coordinate-grid-hud.html#autotoc_md278',1,'']]],
  ['system_20grid_20hud_51',['Coordinate System, Grid &amp;amp; HUD',['../md_source_2user-guide_2coordinate-grid-hud.html',1,'']]]
];
